services:
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: neoarchlinux.org_php
    env_file:
      - .env
    volumes:
      - ./public:/var/www/html/public:ro
      - ./routes:/var/www/html/routes:ro
      - ./src:/var/www/src:ro
      - ./app/mirrors:/var/mirrors:rw
      - ./app/gnupg:/srv/http/.gnupg:rw
      - ./app/man:/app/man:ro
    restart: unless-stopped
    networks:
      - neoarchlinux.org
    user: "0:0"

  nginx:
    image: nginx:stable-alpine
    container_name: neoarchlinux.org_nginx
    depends_on:
      - php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/error.nginx.conf:/etc/nginx/error.nginx.conf:ro
      - ./public:/var/www/html/public:ro
      - ./routes:/var/www/html/routes:ro
      - ./src:/var/www/src:ro
      - ./app/ssl:/etc/nginx/ssl:ro
      - ./app/logs/nginx:/var/log/nginx:rw
      - ./app/mirrors:/var/mirrors:ro
      - ./app/isos/out:/app/isos-out:ro
    restart: unless-stopped
    networks:
      - neoarchlinux.org

  postgres:
    image: postgres:18-alpine
    container_name: neoarchlinux.org_postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./app/db_data:/var/lib/postgresql/data:rw
    restart: unless-stopped
    networks:
      - neoarchlinux.org

  package-updater:
    build:
      context: .
      dockerfile: docker/package-updater.Dockerfile
    container_name: neoarchlinux.org_package_updater
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./app/logs/package-updater:/var/log/package-updater:rw
      - ./app/mirrors:/app/mirrors:rw
      - ./app/man:/app/man:rw
    restart: always
    networks:
      - neoarchlinux.org

  iso-builder:
    build:
      context: .
      dockerfile: docker/iso-builder.Dockerfile
    container_name: neoarchlinux.org_iso_builder
    depends_on:
      - nginx
    volumes:
      - ./app/isos:/app/isos:rw
    restart: unless-stopped
    networks:
      - neoarchlinux.org
    privileged: true

networks:
  neoarchlinux.org:
    external: true
