[options]
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/
HoldPkg     = pacman glibc
#XferCommand = /usr/bin/curl -L -C - -f -o %o %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
Architecture = x86_64

#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

#UseSyslog
#Color
NoProgressBar
CheckSpace
VerbosePkgLists
ParallelDownloads = 5
DownloadUser = alpm
DisableSandbox

SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

[matrix]
SigLevel = Never
Server = http://neoarchlinux.org_nginx/neoarch/$repo/os/$arch

[system]
Server = http://neoarchlinux.org_nginx/artix/$repo/os/$arch

[world]
Server = http://neoarchlinux.org_nginx/artix/$repo/os/$arch

[galaxy]
Server = http://neoarchlinux.org_nginx/artix/$repo/os/$arch

[lib32]
Server = http://neoarchlinux.org_nginx/artix/$repo/os/$arch

[extra]
Server = http://neoarchlinux.org_nginx/arch/$repo/os/$arch

[multilib]
Server = http://neoarchlinux.org_nginx/arch/$repo/os/$arch

#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs